### PR TITLE
Merge development into master

### PR DESCRIPTION
**Pull request by p0pr0ck5**

### CODE REVIEW

**Comment by hy05190134** [comment]
Good, I will watch continually

**Comment by p0pr0ck5** [comment]
Planning on releasing a v0.6 tag tomorrow.

**Comment by hy05190134** [comment]
everyone can review the code?

**Comment by p0pr0ck5** [comment]
Please feel free to leave comments if you have them.

**Comment by hy05190134** [comment]
@p0pr0ck5  OK, pleasure.

**Comment by hy05190134** [comment]
screen shot 2016-01-27 at 10 53 05 am
red cross mean it will not be added into master?

**Comment by p0pr0ck5** [comment]
It will be added. That icon indicates the unit test on Travis CI failed for that particular commit. More recent commits have fixed the issues noted.

All of the commits noted here will be present on the master branch once this is merged.

**Pull request merged**
