### PR TITLE
gitignore & logging modularization

### PR DESCRIPTION
**Pull request by splitice**
Sorry, should have made two feature branches.

1) Just a gitignore.... IntelliJ + LUA plugin is quite a nice experience :)
2) 
What do you think about it, from our perspective we have an existing logging system that we would like to tie in - by passing this as a function to set_option rather than a string we can do this without requiring a code modification.

Documentation is not updated in this commit, waiting to hear your opinion first.

Usage:
```
waf.set_option("event_log_target", waf.loggers.socket("host","path",size,flush))
```

Performance changes: No change expected, slight improvement from less table lookups. Possibly slight improvement from the configuration table being smaller - but micro.

### CODE REVIEW

**Comment by splitice** [comment]
It has also crossed my mind to leave file_logger, socket_loger as nil until first usage. This way resty.logger would not be required unless in use (less memory, less dependencies if not running OpenResty).

**Comment by p0pr0ck5** [comment]
I think the idea of making the logging modular isn't bad, but I'm not a fan of this approach. I'd rather not ask users to configure their logging setup as a raw Lua function- that seems dirty to me. We can probably instead introduce a separate option that a user could use to pass in a function as a logging target, and instead of hitting the local lookup table, bounce to their function.

The socket and file loggers are dependent on modules distributed with FreeWAF itself (in the inc directory), so there's no dependency issue. And since modules are loaded and cached globally, the only runtime overhead is when the module is loaded on the very first request for the worker. The memory overhead of these modules is absolutely minimum (a few KB at most). That said, I am a fan of lazy instantiation in the name of efficiency, so kudos for the suggestion :D

**Comment by splitice** [comment]
True the dependency thing was a bit of an after thought. Using a lua function doesn't bother me but I suppose it could bother others.

Not an issue at the moment, but it would make deployment pretty easy if it was just waf.lua (and using luarocks or similar to bring deploy compiled modules).

A possible API could be something like - 
```
waf.set_logger("file",{opt1="a"})
```

or

```
waf.set_logger_file("opt1","opt2")
```

That sets a good precedent for other possible options, also gets code completion if using an IDE with support :)

**Comment by p0pr0ck5** [comment]
Going to close this as stale. There are some good ideas and discussion here, and we might revisit this in the future.

**Pull request closed without merging**
