### PR TITLE
Merge modsec2freewaf into development

### PR DESCRIPTION
**Pull request by p0pr0ck5**
This covers a big chunk of the translation work and gets us to a good spot to start mopping up missed features or smaller bugs. I also want to tag a new release relatively soon and want to start getting wrapped up for that.

### CODE REVIEW

**Comment by hy05190134** [comment]
Is it mean the freewaf can read the mod security rules and handle it?

**Comment by p0pr0ck5** [comment]
Yes, please have a look at `tools/modsec2lua-resty-waf.pl` and https://www.cryptobells.com/reintroducing-lua-resty-waf/

**Comment by hy05190134** [comment]
Does the lua-resty-waf have plan to merge into openresty?

**Comment by hy05190134** [comment]
@p0pr0ck5  I have already read the reintroduction of lua-resty-waf, and hope it can be merged into openresty, you have throw so much hard work into FreeWaf

**Comment by p0pr0ck5** [comment]
I doubt this will be merged into OpenResty, and that is not a goal for this project. There are many third-party resty libraries that are not part of OpenResty.

**Comment by hy05190134** [comment]
@p0pr0ck5  what's the goal of the lua-resty-waf?

**Pull request merged**
